name: files
version: 0.0.1-dev.1
author: Dart Authors <misc@dartlang.org>
homepage: https://github.com/dart-lang/files.dart
description: A filesystem API with implementations for multiple environments
dependencies:
  quiver: '>=0.19.0-dev.3 <1.0.0'
dev_dependencies:
  unittest: '>=0.9.2 <=0.12.0'
