name: files
version: 0.0.1-dev
author: Dart Authors <misc@dartlang.org>
homepage: https://github.com/dart-lang/files.dart
description: A filesystem API with implementations for multiple environments
dependencies:
  quiver:
    git:
      url: https://github.com/google/quiver-dart.git
      ref: future_stream
dev_dependencies:
  unittest: '>=0.9.2 <=0.12.0'
